INJIMOB-1566 Description updated for masterData 6 APIs
mosip/admin-services pull request #1011
Opened 2024-07-05 12:58 UTC by hegdenitin

**Added description for following APIs**
GetBiometricTypes
GetBiometricTypesByLangcode
GetDeviceHistory
GetDocCategory
GetDocCategoryByLangCode
GetDocType_DocCatByAppID

2024-07-22 11:23 UTC, mohanachandran-s requested changes

2024-07-23 16:32 UTC, hegdenitin commented on apitest/src/main/resources/masterdata/LocationController/CreateLocationData.yml
> -   MasterData_CreateLocationData_All_Valid_Smoke_Sid:
reverted other changes

2024-08-02 13:14 UTC, hegdenitin commented
pushed latest code changes

2024-08-07 06:15 UTC, mohanachandran-s approved these changes

2024-08-13 07:08 UTC, lsivanand approved these changes

2024-08-14 17:46 UTC, merged