MOSIP-35957 uniqueIdentifier for masterData
mosip/admin-services pull request #1088
Opened 2024-10-01 05:57 UTC by maheswaras

Added unique identifier for first 113 API testcases

2024-10-03 09:31 UTC, mohanachandran-s requested changes

2024-10-03 09:31 UTC, mohanachandran-s commented on api-test/src/main/resources/masterdata/Device/CreateDevice.yml
> +	"validityDateTime": "$TIMESTAMP$",
This should be unchanged

2024-10-03 09:31 UTC, mohanachandran-s commented on api-test/src/main/resources/masterdata/Device/CreateDevice.yml
> -	"validityDateTime": "$IGNORE$",
This should be unchanged

2024-10-03 09:31 UTC, mohanachandran-s commented on api-test/src/main/resources/masterdata/Device/UpdateDevice.yml
> -	"validityDateTime": "$IGNORE$",
This should be unchanged

2024-10-03 09:31 UTC, mohanachandran-s commented on api-test/src/main/resources/masterdata/Device/UpdateDevice.yml
> -	"validityDateTime": "$IGNORE$",
This should be unchanged

2024-10-08 08:58 UTC, maheswaras commented on api-test/src/main/resources/masterdata/Device/CreateDevice.yml
> +	"validityDateTime": "$TIMESTAMP$",
Updated properly

2024-10-08 09:31 UTC, mohanachandran-s approved these changes

2024-10-09 07:00 UTC, ase-101 approved these changes

2024-10-09 09:01 UTC, merged