MOSIP-11008
mosip/admin-services pull request #121
Opened 2021-01-13 08:37 UTC by jpnayak007

2021-01-20 05:47 UTC, gsasikumar requested changes

2021-01-20 05:55 UTC, jpnayak007 commented on admin/admin-service/src/main/java/io/mosip/admin/packetstatusupdater/service/impl/PacketStatusUpdateServiceImpl.java
> +		}else {
If the user has gobal_admin authority, then there should be no zone validation for him. So we are checking if token contains the global_admin role , if it is there , then no need to do zone validation for the user. I will simplify the condition, as I can see 3 lines can be reduced.

2021-01-20 06:03 UTC, jpnayak007 commented on admin/admin-service/src/main/java/io/mosip/admin/packetstatusupdater/service/impl/PacketStatusUpdateServiceImpl.java
> +				throw new AccessDeniedException(validationErrorsList.get(0).getMessage());
I will add logs in all error scenarios. I had not added any here as previously there were no logs for any errors in the class. For validations error list we are generally throwing AuthNException which gives 500 http code . But here to show the proper error I changed it to access denied exception

2021-01-20 06:09 UTC, jpnayak007 commented on admin/admin-service/src/main/java/io/mosip/admin/packetstatusupdater/service/impl/PacketStatusUpdateServiceImpl.java
> +			RestTemplate restTemplate1=new RestTemplate();
If I auto-wire the restTemplate loads a bean defined in auth-adpter config. This bean accepts the token received from user as default  header and sends them for api calls for which 403_forbidden error is received while making a call to registration_transaction api service . However by using a generic rest template object I am able to add regproc token received in the newly created method 'setRequestHeader()' and fetch results from transaction api.

2021-01-21 09:26 UTC, gsasikumar approved these changes

2021-01-21 09:26 UTC, merged