adding location hierarchy list in client-setting api
mosip/admin-services pull request #146
Opened 2021-03-17 09:51 UTC by neosoftSatish

adding location hierarchy list in client-setting api

2021-03-17 12:09 UTC, ase-101 commented
@neosoftSatish  seems like your commit is included old files as completely new commits. Only your files and your changes should be part of the PR

2021-03-19 13:58 UTC, neosoftSatish commented
> @neosoftSatish seems like your commit is included old files as completely new commits. Only your files and your changes should be part of the PR

I have added only those files which were not present in the project. I have not committed any old files.

2021-03-23 12:59 UTC, ase-101 requested changes

2021-03-23 12:59 UTC, ase-101 commented on admin/kernel-masterdata-service/src/main/java/io/mosip/kernel/masterdata/controller/LocationHierarchyController.java
> +	@PreAuthorize("hasAnyRole('ZONAL_ADMIN','GLOBAL_ADMIN','INDIVIDUAL','PRE_REGISTRATION','REGISTRATION_PROCESSOR')")
Add Default role

2021-03-23 12:59 UTC, ase-101 commented on admin/kernel-syncdata-service/src/main/java/io/mosip/kernel/syncdata/config/Config.java
> +	@Primary
remove this code, and 
private RestTempalate restTemplate

2021-03-23 12:59 UTC, ase-101 commented on admin/kernel-syncdata-service/src/main/java/io/mosip/kernel/syncdata/config/MosipEnvironment.java
> +	private Environment environment;
directly inject required property with @Value("${}") in the required class, Please remove this class

2021-03-23 12:59 UTC, ase-101 commented on admin/kernel-syncdata-service/src/main/java/io/mosip/kernel/syncdata/utils/SyncMasterDataServiceHelper.java
> +	@Qualifier("authRestTemplate")
@qualifier not required, restTemplate bean is already available

2021-03-23 12:59 UTC, ase-101 commented on admin/kernel-syncdata-service/src/main/java/io/mosip/kernel/syncdata/utils/SyncMasterDataServiceHelper.java
> +				// throw new SyncServiceException(validationErrorsList);
you need to throw this exception

2021-03-23 12:59 UTC, ase-101 commented on admin/kernel-syncdata-service/src/main/resources/application-local.properties
> +mosip.kernel.idobjectvalidator.masterdata.locationhierarchylevels.rest.uri = https://dev.mosip.net/v1/masterdata/locationHierarchyLevels
mosip.kernel.masterdata.locationhierarchylevels.url=https://dev.mosip.net/v1/masterdata/locationHierarchyLevels

2021-03-23 14:31 UTC, merged