Develop
mosip/admin-services pull request #301
Opened 2021-08-02 16:40 UTC by Shilpa-Manjunath

2021-08-03 12:30 UTC, dhanendra06 requested changes

2021-08-03 12:30 UTC, dhanendra06 commented on admin/kernel-masterdata-service/src/main/java/io/mosip/kernel/masterdata/service/impl/ValidDocumentServiceImpl.java
> +	private String supportedLang;
use mandatory language and pass the same while creating mapping

2021-08-03 12:42 UTC, dhanendra06 commented on admin/kernel-masterdata-service/src/main/java/io/mosip/kernel/masterdata/service/impl/ValidDocumentServiceImpl.java
> +	private String supportedLang;
changed the attribute name

2021-08-04 04:50 UTC, dhanendra06 approved these changes

2021-08-04 09:14 UTC, urviljoshi approved these changes

2021-08-04 09:15 UTC, merged